### ISSUE TITLE
[Epic] Active Effects

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#171]
This issue tracks the progress of the Active Effects update that is part of `0.11.x`.

The main goal of this update is to provide a useful and feature-rich interface to track and edit effects on actor and item documents.

### Interfaces 
- [ ] [Feat] Actor Effects Page.
- [ ] [Feat] Item Effects Page.
- [ ] [Feat] Action Effects Page.
- [ ] [Feat] Effect Configuration Interface

### Functionality
- [ ] [Feat] Prepare a selectable list of effects for people to choose from.
- [ ] [Feat] Transfer active effects on item use.
- [ ] [Feat] Transfer passive effects to the actor on item drop.
- [ ] [Feat] Allow for stacking of effects.
- [ ] [Feat] Allow formulas in value fields.
- [ ] [Feat] Allow arithmetic in value fields.
- [ ] [Feat] Allow effects to be applied to tokens.
- [ ] [Feat] Set priority for effects.
- [ ] [Feat] Allow calling macros when active effects are applied to an actor.
- [ ] [Feat] Shortcut custom effects.
- [ ] [Feat] Allow `@flags` in `getRollData()`.
- [ ] [Feat] Allow effects to affect both base and derived data.
- [ ] [Feat] Add roll once expressions.

**Comment by Pjb518** [comment]
I think think this makes sense to be part of the `0.11.0` milestone, since its completion is not planned for `0.11.0`. Moving this back to `0.11.x`.
