### ISSUE TITLE
[Epic] Deprecations & Updates to support v12

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#273]
- [x] Update `ChatMessage.user` to `ChatMessage.author`.
- [x] Update `MeasuredTemplate.user` to `MeasuredTemplate.author`.
- [ ] Update `progressBar` to new notification system.
- [ ] `Scene#grid` is now a `BaseGrid/SquareGrid/HexagonalGrid` instance.
