### ISSUE TITLE
[Epic] Genie - Grants & Bonuses

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#297]
The following need to be completed to close out the Genie release series.

### General Upgrades
- [x] #298
- [x] #299

### Bonus System
- [x] [Feat] Convert Ability bonus fields to a Bonus.
- [x] [Feat] Convert Skill bonus fields to a Bonus.
- [x] #300
- [x] #301
- [x] [Feat] Implement Bonus Manager.

### Context System
- [x] [Feat] Add contexts for abilities.
- [x] [Feat] Add contexts for skills.
- [x] #303

### Grant System
- [x] #304
- [x] #305
- [x] #306
- [x] #307
- [x] #308
- [x] #309
- [x] #311
- [x] #310
- [x] #312
- [x] #313
- [x] #315
- [x] #316
- [x] #317
- [x] #318

**Comment by NekroDarkmoon** [comment]
Completed as part of 0.16.54. Closing the release series.
