### ISSUE TITLE
[Feat] Allow selection of consumers at item activation

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#336]
### Tasks
- [x] Add label config to consumers. 
- [x] Add default property and config to consumers.
- [x] Add a section on the activation dialog to select and deselect consumers. 
- [x] Update methods to only use consumers that are selected or default consumer in the case of fast forward rolling.

### Original Issue
Some features have multiple choices to be consumed, so it would be nice to have the same "Select X Automatically in Roll Prompt" as rolls, so a player can make the choice at the time of using the feature.
By nchezrony
