### ISSUE TITLE
[Chore] Retouch Actions

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#465]
Update and rework the actions system to be more in line with the rest the new features recently added. 

### Tasks
- [ ] Convert to typescript.
- [ ] Add data model support.
- [ ] Update ActionsManager to extent Map instead of a proxy.
- [ ] Update API methods.
- [ ] Update references.
