### ISSUE TITLE
[Chore] Retouch Chat Cards

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#466]
Update existing system chat cards to use new features available in v12. 

### Tasks
- [x] Add data models for chat cards.
- [x] Add roll type card for checks and saves. 
- [x] Add item type card for activation cards. 
- [x] Add rolltable type for rolltables. 
- [x] Update styling of chat cards. 
- [x] Update creation method. 
- [x] Update preparation of chat cards.

### Related Issues
- [x] #284 
- [x] #76
